---
- name: Delete ec2 instance
  ec2:
    region: "{{ region }}"
    image: "{{ ami }}"
    exact_count: 0
    count_tag:
      Name: "{{ project }}-instance"
      Project: "{{ project }}"

- name: Delete s3 bucket
  s3_bucket:
    name: "{{ s3bucketname }}"
    region: "{{ region }}"
    state: absent
    force: yes

