---
# Play to create s3 bucket

- name: Create s3 bucket
  s3_bucket:
    name: "{{ s3bucketname }}"
    region: "{{ region }}"
    state: present
    versioning: no
    policy: "{{ lookup('template','s3policy.json.j2') }}"
    tags:
      project: task
  register: s3_bucket
  tags: s3